CREATE TABLE INSTRUCTOR(
instructorID NUMBER PRIMARY KEY,
instructorName VARCHAR2(45)
);
CREATE TABLE MODULE(
moduleCode VARCHAR2(10) PRIMARY KEY,
moduleName VARCHAR2(45)
);
CREATE TABLE STUDENT(
studentNo NUMBER PRIMARY KEY,
studentName VARCHAR2(45)
);
CREATE TABLE REGISTRATION(
moduleCode VARCHAR2(10),
studentNo NUMBER,
FOREIGN KEY(moduleCode)
REFERENCES MODULE(moduleCode),
FOREIGN KEY(studentNo)
REFERENCES STUDENT(studentNo)
); 

CREATE SEQUENCE instructorID
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE SEQUENCE studentNo
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO INSTRUCTOR (instructorID, instructorName)
VALUES (INSTRUCTORID.NEXTVAL, 'Nayeon');
INSERT INTO INSTRUCTOR (instructorID, instructorName)
VALUES (INSTRUCTORID.NEXTVAL, 'Sana');
INSERT INTO MODULE (moduleCode, moduleName)
VALUES ('MAT021', 'Math');
INSERT INTO MODULE (moduleCode, moduleName)
VALUES ('PHY001', 'Physics');
INSERT INTO STUDENT (studentNo, studentName)
VALUES (STUDENTNO.NEXTVAL, 'Satoru');
INSERT INTO STUDENT (studentNo, studentName)
VALUES (STUDENTNO.NEXTVAL, 'Tanjiro');
INSERT INTO REGISTRATION (moduleCode, studentNo)
VALUES ('MAT021', 7);
INSERT INTO REGISTRATION (moduleCode, studentNo)
VALUES ('PHY001', 8)

select INSTRUCTOR.INSTRUCTORNAME, MODULE.MODULENAME from
INSTRUCTOR, MODULE;

CREATE OR REPLACE PROCEDURE REGISTER (n_ModuleCode IN
VARCHAR2,n_student in NUMBER)
AS
i_count NUMBER;
BEGIN
SELECT COUNT(*)
into i_count
FROM REGISTRATION
WHERE ModuleCode = n_ModuleCode
AND studentNo = n_student;
IF i_count = 0 THEN
INSERT INTO REGISTRATION (ModuleCode, studentNo)
VALUES (n_ModuleCode, n_student);
END IF;
END;
/
BEGIN
REGISTER('James',77);
END;
/ 

